id: PA42733A1
initial_creation_type: input
source_metadata:
  title: Patrul Rinpoche Series
  language: bo
  description: 'Texts by and about the great Rimé master, Dza Patrul Orgyen Jigme
    Chökyi Wangpo (rdza dpal sprul o rgyan ''jigs med chos kyi dbang po, 1808–1887):'
  volume:
    5f32c4bac51245d49e9bad7ca69f9465:
      title: Advice for Alak Dongak
      parent: Advice
    1215a5bde7a64452a7ae709334b35cfa:
      title: Advice to Lama Rigdzin Gyatso on Understanding the Influence of Companions
        and Avoiding and Adopting Them Accordingly
      parent: Advice
    4e06e57b8280408398443ffef3925160:
      title: Nine Considerations and Criteria for Benefiting Beings
      parent: Advice
    8c0618647291415ea2d202c338854296:
      title: The Precious Treasury of Written Instruction Transmitted One-to-One
      parent: Advice
    44d0342808b84f429f5f0cbe810abd53:
      title: Yearning for Mountain Solitude
      parent: Advice
    6b65542fe6484558994045242c008741:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Aspiration Prayers
    c0009e7ae19b46108dea22e43e194460:
      title: Biography of Patrul Rinpoche
      parent: Biography
    8aebd995572f44ae83d2e70e5d4d77fe:
      title: Prayer to the Lineage of the Bodhicaryāvatāra
      parent: Bodhicaryāvatāra
    7c41585611ab4eb089c3658b551d56d4:
      title: 'The Brightly Shining Sun: A Step-by-Step Guide to Meditating on the
        Bodhicaryāvatāra'
      parent: Bodhicaryāvatāra
    8c723f1a9a4a43c6bd7b99b5176663e8:
      title: A Brief Guide to the Stages and Paths of the Bodhisattvas
      parent: Buddhist Philosophy & Teachings
    12c04ac50089445fa1ad1d6756c6964a:
      title: A Brief Introduction to the Bardos
      parent: Buddhist Philosophy & Teachings
    1dd54af9c9e44c54b2e3ff303c31406a:
      title: An Essential Instruction on Refuge and Bodhichitta
      parent: Buddhist Philosophy & Teachings
    279473ada64948438369f5a9faccd9a4:
      title: An Instruction on the View of the Mahāyāna – Clarifying the Two Truths
      parent: Buddhist Philosophy & Teachings
    5996194068c34464bc4b2cf15e97f1a4:
      title: Preliminary Points to be Explained When Teaching the Buddha's Word or
        the Treatises
      parent: Buddhist Philosophy & Teachings
    d0d50006d81d476baacda9788ea45f5a:
      title: 'The Concentrated Seed: How to Distinguish the Tenets of Non-Buddhist
        and Buddhist Schools'
      parent: Buddhist Philosophy & Teachings
    b402534fe19e41279110e3d01cf17eec:
      title: Advice on How to Put the Meaning of the Natural Great Perfection into
        Practice
      parent: Dzogchen
    64bd46e82e234ea6b9011a6b840bfa42:
      title: 'Self-Liberating Meditation: A Profound Method for Attaining Enlightenment
        according to the Ultimate Great Perfection'
      parent: Dzogchen
    9668efafd7594de7991e68cfd8f8daa9:
      title: Brief Guide to the Stages of Visualization for the Ngöndro Practice
      parent: Ngöndro
    6b94122930ee4c349efcbd9846d2f6d0:
      title: 'A Garland of Fresh Utpala Flowers: A Brief Synopsis of the Treasury
        of Precious Qualities, A Treatise of Pith Instructions'
      parent: Pedagogy
    4d441ee99370451686abc7883b317f36:
      title: 'Mirror of the Mind: Prologue to The Treasury of Precious Qualities'
      parent: Pedagogy
    27af4c9db3b841ffbe8c7a237d07abbe:
      title: In Praise of Glorious Vajrasattva
      parent: Praise
    4098d3bca272424ea746ee573167ca68:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Praise
    1c0252be38f441e48a04b1dbf94932f1:
      title: 'Excellent Explanation from the Scriptural Tradition: A Brief Guide to
        the Stages of Meditating on the General Themes of the Ornament to the Prajñāpāramitā'
      parent: Prajñāpāramitā
    002568c4634444688f97b85fdda2011f:
      title: 'Nectar of Lunar Crystal: A Prayer to Orgyen Chökyi Wangpo'
      parent: Prayers
    7d6873a2b74c430aa0d036b3c830ed30:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    5dd84f75f4f543c0a3bffd097a2c7a80:
      title: Prayer to Machik Labdrön
      parent: Prayers
    5e254f3b9838471c85e2d029bd9c4a27:
      title: Prayer to Śāntideva and Dam, Tsang and Jam of Katok
      parent: Prayers
    f4b2d769b90b4049b6f8fe5752bd4582:
      title: Brief Windhorse Practice of Tārā
      parent: Prayers & Practices
    7c87f9ac30e8443aa8d130798f2f2191:
      title: Temple Dedication Prayer
      parent: Prayers & Practices
    63ec7560a7304108ae717495ca2bbfbf:
      title: A Brief Mañjuśrī Sādhana
      parent: Sādhanas
    663469b93db94cb18528602f07779878:
      title: The Method for Observing the Eight-Branched One-Day Vow
      parent: Sojong
    4c52eb8efef240719128a60a4ea62d02:
      title: The Special Teaching of the Wise and Glorious King – Commentary
      parent: Special Teaching of the Wise and Glorious King
    ee3df60d83664ff3a6e08cefc1a046a8:
      title: The Special Teaching of the Wise and Glorious King—Root Text
      parent: Special Teaching of the Wise and Glorious King
    d8bae3c098da46608a4c4fdc3d314070:
      title: The Special Teaching of the Wise and Glorious King—Root Text (arranged
        in Tibetan-English verses)
      parent: Special Teaching of the Wise and Glorious King
    84eb89a5e57946fc94fed755f9bc86d9:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Topical Outlines
    57b59d06918942f39fe6129bdf518788:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Topical Outlines
    7764baf089094335b4c818239bccd606:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Topical Outlines
    0905a0caa3f54431825e00208ea9d837:
      title: 'Transference: Enlightenment Without Meditation (Compilation)'
      parent: Transference (Phowa)
    78a0db6a9b794653a04fb0b92e355273:
      title: The Ritual of the Bodhisattva Vow According to the Tradition of Patrul
        Rinpoche
      parent: Vows & Commitments
created_at: '2022-03-01T01:13:56.749984'
last_modified_at: '2022-03-01T01:13:56.749986'
